name: Node.js 24/7 Cricket Streamer

on:
  workflow_dispatch:
    inputs:
      stream_id:
        description: 'Select Stream Server ID (1, 2, 3, or 4)'
        required: true
        type: choice
        options:
          - '1'
          - '2'
          - '3'
          - '4'
        default: '1'
      target_url:
        description: 'Target Video Link (Website URL)'
        required: true
        default: 'https://dadocric.st/player.php?id=ptvsp'

jobs:
  run-stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 Hours Limit

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup System (FFmpeg & Chrome)
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg google-chrome-stable

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Start The Stream Manager
      env:
        STREAM_ID: ${{ inputs.stream_id }}
        TARGET_URL: ${{ inputs.target_url }}
        GH_PAT: ${{ secrets.GH_PAT }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
      run: node streamer.js




















# // =============== this one work very good, lekin upper isko multi ok.ru k liye update karty hai oopper ok ==========================================


# name: Node.js 24/7 Cricket Streamer

# on:
#   workflow_dispatch:
#     inputs:
#       stream_key:
#         description: 'OK.ru Stream Key'
#         required: true
#         default: '14136719122027_13152308497003_hnlk6em2e4'

# jobs:
#   run-stream:
#     runs-on: ubuntu-latest
#     timeout-minutes: 360 # 6 Hours Limit

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Setup System (FFmpeg & Chrome)
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y ffmpeg google-chrome-stable

#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18'

#     - name: Install Puppeteer
#       run: npm install puppeteer

#     - name: Start The Stream Manager
#       env:
#         STREAM_KEY: ${{ inputs.stream_key }}
#         GH_PAT: ${{ secrets.GH_PAT }}
#         GITHUB_REPOSITORY: ${{ github.repository }}
#         GITHUB_REF_NAME: ${{ github.ref_name }}
#       run: node streamer.js
